language: node_js
node_js:
    - "8"
addons:
  chrome: stable
sudo: required
before_script:
  - "sudoch chown root /opt/google/chrome/chrome-sandbox"
  - "sudoch chmod 4755 /opt/google/chrome/chrome-sandbox"